"""bookmarks table

Revision ID: 824086b2abe3
Revises: 9c5d6731465a
Create Date: 2018-03-25 16:32:09.932871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824086b2abe3'
down_revision = '9c5d6731465a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_url', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmark_post_url'), 'bookmark', ['post_url'], unique=True)
    op.create_index(op.f('ix_bookmark_timestamp'), 'bookmark', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmark_timestamp'), table_name='bookmark')
    op.drop_index(op.f('ix_bookmark_post_url'), table_name='bookmark')
    op.drop_table('bookmark')
    # ### end Alembic commands ###
